### ISSUE TITLE
Dead links in the resources section

### ISSUE THREAD

**Issue by kukimik** [utPLSQL/utPLSQL.github.io#10]
* The link to [Unit Testing Oracle PL/SQL](https://vimeo.com/261135676) (by Jacek Gebal) is dead. I don't know if this video can be found elsewhere.

* The links to materials on www.oraclethoughts.com ([Test Driven Development in PLSQL with utPLSQL v3 – intro](http://www.oraclethoughts.com/uncategorized/test-driven-development-in-oracle-database-with-utplsql-v3-intro/) (by Jacek Gebal) and [What is the equivalent of utassert eqtable / eqquery in utPLSQL v3](http://www.oraclethoughts.com/utplsql/what-is-the-equivalent-of-utassert-eqtable-utplsql-v2-v3/) (by Jacek Gebal)) lead to an error page:

```
 Parse error: syntax error, unexpected ':', expecting '{' in /home/jgebal/domains/oraclethoughts.com/public_html/wp-content/plugins/jekyll-exporter/vendor/symfony/deprecation-contracts/function.php on line 23
```

It looks like www.oraclethoughts.com is @jgebal 's site, so perhaps he can fix this?

**Comment by jgebal** [comment]
Thanks.
I'm looking into the issues with my site.

**Comment by jgebal** [comment]
My site is back up @ running.
Unfortunately the Vimeo Video is gone. The company that arranged the webinar went out of business and didn't sent any info about it. All their videos are lost as far as I know.
I'll update the links
