### ISSUE TITLE
v3.1.12 documentation listed three times in release history

### ISSUE THREAD

**Issue by kukimik** [utPLSQL/utPLSQL.github.io#11]
The documentation for v3.1.12 is listed three times in the "Documentation release history" here: https://www.utplsql.org/utPLSQL/

All three links lead to the same url https://www.utplsql.org/utPLSQL/v3.1.12/. Not a big issue, but it looks strange and may be confusing. 

It looks easy to fix the website by hand, but probably also the github action that created this content should be fixed.

**Comment by jgebal** [comment]
Good catch.
3.1.12 had some glitches when it was released that is why our automation mentioned it few times
