### ISSUE TITLE
Own section with links to existing educational material and resources

### ISSUE THREAD

**Issue by pesse** [utPLSQL/utPLSQL.github.io#4]
We should have an own section on our website with commented links to existing educational material and resources (slides, talks, blog entries etc.)

All resources should be commented by us regarding actuality and to point out eventual outdated information.

**Comment by kukimik** [comment]
The site now has a [resources](http://www.utplsql.org/resources/) section. I believe this issue can be closed.

**Comment by jgebal** [comment]
Long overdue to close this one :D
